version: "3.8"

services:
  my_devcontainer:
    image: mcr.microsoft.com/vscode/devcontainers/typescript-node:14
    volumes:
      - .:/workspace
      - /workspace/
      - /workspace/packages/app/node_modules
      - /workspace/packages/backend/node_modules
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      POSTGRES_HOST: postgres_db
      POSTGRES_USER: postgres_username
      POSTGRES_PASSWORD: postgres_password
  postgres_db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres_username
      POSTGRES_PASSWORD: postgres_password
